version: "3.8"

networks:
  jenkins_net:
    driver: bridge

volumes:
  jenkins_data: {}

services:
  jenkins:
    build:
      context: .
      args:
        JENKINS_UID: ${JENKINS_UID}
        JENKINS_GID: ${JENKINS_GID}
        JENKINS_USER: ${JENKINS_USER}
        JENKINS_GROUP: ${JENKINS_GROUP}
        JENKINS_REF: ${JENKINS_REF}
        JENKINS_HOME: ${JENKINS_HOME}
        JENKINS_SHA: ${JENKINS_SHA}
        JENKINS_URL: ${JENKINS_URL}
        PLUGIN_CLI_URL: ${PLUGIN_CLI_URL}
      dockerfile: alpine.dockerfile
    env_file: .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${AGENT_PORT}:${AGENT_PORT}
    restart: unless-stopped
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins_net
